default_context:
  project_name: 'Dreamcatcher'
  project_slug: 'dreamcatcher'
  domain_main: 'dreamcatcher.com'
  domain_staging: 'stag.dreamcatcher.com'
  docker_swarm_stack_name_main: 'dreamcatcher-com'
  docker_swarm_stack_name_staging: 'stag-dreamcatcher-com'
  secret_key: '910bc50964983a8bf99262ed68ebb949ff42626c285385988feeb5eb599d392b'
  first_superuser: 'admin@dreamcatcher.com'
  first_superuser_password: 'faeb8a1effa662c2ceef1bba1068b46f4505c1a781ef44036abc610333ea9d1e'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.dreamcatcher.com", "https://stag.dreamcatcher.com", "https://dreamcatcher.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@dreamcatcher.com'
  postgres_password: '3a2d1e1cd07f91123953359b02b3ab6bac76ebadb714f9c8b43c00e9acd125c4'
  pgadmin_default_user: 'admin@dreamcatcher.com'
  pgadmin_default_user_password: 'faeb8a1effa662c2ceef1bba1068b46f4505c1a781ef44036abc610333ea9d1e'
  traefik_constraint_tag: 'dreamcatcher.com'
  traefik_constraint_tag_staging: 'stag.dreamcatcher.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:faeb8a1effa662c2ceef1bba1068b46f4505c1a781ef44036abc610333ea9d1e'
  sentry_dsn: 'https://fc5d8c0a1ce742c593bfa6e143764a10@o407856.ingest.sentry.io/5277608'
  docker_image_prefix: 'https://github.com/sbathgate/dreamcatcher'
  docker_image_backend: 'https://github.com/sbathgate/dreamcatcher/backend'
  docker_image_celeryworker: 'https://github.com/sbathgate/dreamcatcher/celeryworker'
  docker_image_frontend: 'https://github.com/sbathgate/dreamcatcher/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
